// src/utils/translateTeams.js

const teamTranslations = {
  // Countries
  'Croatia': 'كرواتيا',
  'Belgium': 'بلجيكا',
  'Morocco': 'المغرب',
  'Madagascar': 'مدغشقر',
  'Romania': 'رومانيا',
  'Wales': 'ويلز',
  'Ghana': 'غانا',
  'Haiti': 'هايتي',
  'New Zealand': 'نيوزيلندا',
  'Qatar': 'قطر',
  'Portugal': 'البرتغال',
  'Netherlands': 'هولندا',
  'Italy': 'إيطاليا',
  'Algeria': 'الجزائر',
  'Mexico': 'المكسيك',
  'South Korea': 'كوريا الجنوبية',
  'Spain': 'إسبانيا',
  'France': 'فرنسا',
  'Germany': 'ألمانيا',
  'Brazil': 'البرازيل',
  'Argentina': 'الأرجنتين',
  'England': 'إنجلترا',
  'Egypt': 'مصر',
  'Saudi Arabia': 'السعودية',
  'Japan': 'اليابان',
  'Tunisia': 'تونس',
  'Switzerland': 'سويسرا',
  'Denmark': 'الدنمارك',
  'Uruguay': 'أوروغواي',
  'Senegal': 'السنغال',

  // Clubs
  'Manchester City': 'مانشستر سيتي',
  'Manchester United': 'مانشستر يونايتد',
  'Real Madrid': 'ريال مدريد',
  'Barcelona': 'برشلونة',
  'Liverpool': 'ليفربول',
  'Arsenal': 'أرسنال',
  'Chelsea': 'تشيلسي',
  'Bayern Munich': 'بايرن ميونخ',
  'Juventus': 'يوفنتوس',
  'Inter Milan': 'إنتر ميلان',
  'AC Milan': 'ميلان',
  'Paris Saint-Germain': 'باريس سان جيرمان',
  'PSG': 'باريس سان جيرمان',
  'Tottenham': 'توتنهام',
  'Atletico Madrid': 'أتلتيكو مدريد',
  'Borussia Dortmund': 'بوروسيا دورتموند',
  'Al-Nassr': 'النصر',
  'Al-Hilal': 'الهلال',
  'Al-Ittihad': 'الاتحاد',
  'Al-Ahly': 'الأهلي',
  'Zamalek': 'الزمالك',
  'Inter Miami': 'إنتر ميامي',
  'Al-Ahli': 'الأهلي',
  'Al-Shabab': 'الشباب',
  'Al-Ettifaq': 'الاتفاق',
  'Al-Fateh': 'الفتح',
  'Al-Taawoun': 'التعاون',
  'AC Milan': 'ميلان',
  'Lazio': 'لاتسيو',
  'Roma': 'روما',
  'Napoli': 'نابولي',
  'Fiorentina': 'فيورنتينا',
  'Benfica': 'بنفيكا',
  'Porto': 'بورتو',
  'Sporting CP': 'سبورتينغ لشبونة',
  'Ajax': 'أياكس',
  'PSV': 'آيندهوفن',
  'Feyenoord': 'فينورد',
  'Marseille': 'مارسيليا',
  'Lyon': 'ليون',
  'Monaco': 'موناكو',
  'Leverkusen': 'ليفركوزن',
  'RB Leipzig': 'لايبزيغ',
  'Eintracht Frankfurt': 'آينتراخت فرانكفورت',
  'West Ham': 'وست هام',
  'Aston Villa': 'أستون فيلا',
  'Newcastle': 'نيوكاسل',
  'Brighton': 'برايتون',
  'Sevilla': 'إشبيلية',
  'Villarreal': 'فياريال',
  'Real Betis': 'ريال بيتيس',
  'Real Sociedad': 'ريال سوسيداد',
  // New Additions from Audit
  'Poland': 'بولندا',
  'Nigeria': 'نيجيريا',
  'Chicago Sky': 'شيكاغو سكاي',
  'Washington Mystics': 'واشنطن ميستيكس',
  'Connecticut Sun': 'كونيتيكت صن',
  'Atlanta Dream': 'أتلانتا دريم',
  'Portland Fire': 'بورتلاند فاير',
  'Golden State Valkyries': 'غولدن ستيت فالكيريز',
  'Las Vegas Aces': 'لاس فيغاس آيسز',
  'Los Angeles Sparks': 'لوس أنجلوس سباركس',
  'New York Liberty': 'نيويورك ليبرتي',
  'Toronto Tempo': 'تورونتو تيمبو',
  'San Antonio Spurs': 'سان أنطونيو سبيرز',
  'New York Knicks': 'نيويورك نيكس',
  'Seattle Storm': 'سياتل ستورم',
  'Phoenix Mercury': 'فينيكس ميركوري',
  'Montreal Alouettes': 'مونتريال ألويت',
  'Hamilton Tiger-Cats': 'هاميلتون تايجر كاتس',
  'Winnipeg Blue Bombers': 'وينيبيغ بلو بومبرز',
  'Calgary Stampeders': 'كالغاري ستامبيدرز',
  'Panthers Wroclaw': 'بانثرز فروتسواف',
  'Paris Lights': 'باريس لايتس',
  'Berlin Thunder': 'برلين ثاندر',
  'Firenze Red Lions': 'فيرينزي ريد ليونز',
  'Rhein Fire': 'راين فاير',
  'Vienna Vikings': 'فيينا فايكنجز',
  'Edmonton Elks': 'إدمونتون إلكس',
  'Ottawa RedBlacks': 'أوتاوا ريد بلاكس',
  'Alpine Rams': 'ألباين رامز',
  'London Warriors': 'لندن ووريورز',
  'DC Defenders': 'دي سي ديفندرز',
  'Orlando Storm': 'أورلاندو ستورم',
  'Louisville Kings': 'لويفيل كينجز',
  'St. Louis Battlehawks': 'سانت لويس باتل هوكس',
  'Carolina Hurricanes': 'كارولاينا هوريكانز',
  'Vegas Golden Knights': 'فيغاس غولدن نايتس',
  'Tampa Bay Rays': 'تامبا باي رايز',
  'Detroit Tigers': 'ديترويت تايجرز',
  'Philadelphia Phillies': 'فيلادلفيا فيليز',
  'San Diego Padres': 'سان دييغو بادريس',
  'Boston Red Sox': 'بوسطن ريد سوكس',
  'Baltimore Orioles': 'بالتيمور أوريولز',
  'Washington Nationals': 'واشنطن ناشيونالز',
  'Miami Marlins': 'ميامي مارلينز',
  'New York Yankees': 'نيويورك يانكيز',
  'Cleveland Guardians': 'كليفلاند غارديانز',
  'Cincinnati Reds': 'سينسيناتي ريدز',
  'Kansas City Royals': 'كانساس سيتي رويالز',
  'Atlanta Braves': 'أتلانتا بريفز',
  'Toronto Blue Jays': 'تورونتو بلو جايز',
  'Milwaukee Brewers': 'ميلووكي برويرز',
  'San Francisco Giants': 'سان فرانسيسكو جاينتس',
  'Minnesota Twins': 'مينيسوتا توينز',
  'Chicago White Sox': 'شيكاغو وايت سوكس',
  'St.Louis Cardinals': 'سانت لويس كاردينالز',
  'Texas Rangers': 'تكساس رينجرز',
  'Chicago Cubs': 'شيكاغو كابس',
  'Athletics': 'أوكلاند أثلتيكس',
  'Houston Astros': 'هيوستن أستروز',
  'Pittsburgh Pirates': 'بيتسبرغ بايرتس',
  'Los Angeles Angels': 'لوس أنجلوس أنجلز',
  'Colorado Rockies': 'كولورادو روكيز',
  'Arizona Diamondbacks': 'أريزونا دايموندباكس',
  'Los Angeles Dodgers': 'لوس أنجلوس دودجرز',
  'Seattle Mariners': 'سياتل مارينرز',
  'New York Mets': 'نيويورك ميتس',
  'Willibaldo Garcia': 'ويليبالدو غارسيا',
  'Andrew Moloney': 'أندرو مولوني',
  'Chris Billam-Smith': 'كريس بيلالم سميث',
  'Ryan Rozicki': 'ريان روزيكي',
  'Dalton Smith': 'دالتون سميث',
  'Alberto Puello': 'ألبرتو بويلو',
  'Ricardo Rafael Sandoval': 'ريكاردو رافائيل ساندوفال',
  'Galal Yafai': 'جلال يافعي',
  'Muhammad': 'محمد',
  'Bonfim': 'بونفيم',
  'Wilkens Mathieu': 'ويلكنز ماتيو',
  'Esquiva Falcao': 'إسكيفا فالكاو',
  // More Football Teams & Countries
  'Barracas Central': 'باراكاس سنترال',
  'Huracan': 'هوراكان',
  'Junior': 'جونيور',
  'Atletico Nacional': 'أتلتيكو ناسيونال',
  'Philippines': 'الفلبين',
  'Guam': 'غوام',
  'Kyrgyzstan': 'قيرغيزستان',
  'Kenya': 'كينيا',
  'Latvia U17': 'لاتفيا تحت 17',
  'Albania U17': 'ألبانيا تحت 17',
  'Croatia U21': 'كرواتيا تحت 21',
  'Qatar U20': 'قطر تحت 20',
  'Gibraltar': 'جبل طارق',
  'British Virgin Islands': 'جزر فيرجن البريطانية',
  'Albania': 'ألبانيا',
  'Israel': 'إسرائيل',
  'Portugal U21': 'البرتغال تحت 21',
  'Northern Ireland U21': 'أيرلندا الشمالية تحت 21',
};

/**
 * Translates a team or country name. 
 * Currently returns the original name as the default language is now English.
 * @param {string} name - The original name in English.
 * @returns {string} - The English name.
 */
export default function translateTeam(name) {
  if (!name) return '';
  return name.trim();
}
